name: DogTags
description: "The #1 Ultra Configurable MySQL Supported Tag plugin!"
main: io.chazza.dogtags.DogTags
version: 1.1.6
softdepend: [PlaceholderAPI]

permissions:
  dogtags.gui:
    default: true
  dogtags.clear:
    default: true
  dogtags.info:
    default: true
  dogtags.help:
    default: op
  dogtags.list:
    default: op
  dogtags.perm:
    default: op
  dogtags.create:
    default: op
  dogtags.remove:
    default: op
  dogtags.reload:
    default: op
  dogtags.set:
    default: op